### ISSUE TITLE
ReferenceError: dirname is not defined

### ISSUE THREAD

**Issue by tremby** [Mitscherlich/html-entry-loader#3]
`lib/plugin.js` is trying to call a function called `dirname` but this is not defined.

https://github.com/Mitscherlich/html-entry-loader/blob/fb0c14010cc2f1e3c9b3daec710acf0f40cd4d50/src/plugin.js#L699

**Comment by Mitscherlich** [comment]
thx. This will be fixed in [`v0.1.10`](https://www.npmjs.com/package/html-entry-loader/v/0.1.10)
